manifest-version: 1.0

info:
  name: freeRouter
  description: "freeRouter"
  version: 1.1

app:
  apptype: vm

  resources:
   cpu: 30
   memory: 1024000
   vcpu: 1

   disk:
    - target-dev: hdc
      file: rtr.qcow2

   interfaces:
    - target-dev: net1
    - target-dev: net2
    - target-dev: net3
    - target-dev: net4

   serial:
    - console
    - aux

  startup:
    runtime: kvm
    boot-dev: hd
